
---
output: pdf_document
--- 


---
title: A
---



<style type="text/css">

body, td {
   font-size: 14px;
}
code.r{
  font-size: 12px;
}
pre {
  font-size: 20px
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 5, fig.width = 7,fig.pos = "H", out.extra = "")
pagebreak <- function() {
  if(knitr::is_latex_output())
    return("\\newpage")
  else
    return('<div style="page-break-before: always;" />')
}
```


```{r,warning=F, echo=F, message=F, include=FALSE}
# Required Libraries
# library(arcos)
library(stringr)
library(readr)
library(dplyr)
library(sjlabelled)
library(lubridate)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(pracma)
library(gridExtra)
library(magrittr)
library(multipanelfigure)
library(sandwich)
library(lmtest)
library(estimatr)
library(fixest)
library(data.table)
library(kableExtra)
library(stargazer)
library(rlang)
```





```{r,warning=F, message=F, results='asis', echo=F}
LawNames <- c("OPPDMP_RAND","ePDMP_RAND","PillMill")

Lawdict <- c(`PillMill` = "PillMill",
             `OPPDMP_RAND` = "Operational PDMP",
             `ePDMP_RAND` = "Electronic PDMP")
names = c("Dist2DispBuyerState",
          "Dist2DispBuyerPractitionerState",
          "Dist2DispBuyerRetailPharmacyState","Dist2DispBuyerChainPharmacyState",
          "Dist2DispSellerState")
IDV = paste0(LawNames,"_tr")
pathread <- "G:/My Drive/North Carolina State University/Project - Opioid 3/Data Processed 2/"
pathwrite <- "G:/My Drive/North Carolina State University/Project - Opioid 3/Result/"
figlist <- list()
for (ii in names){
  if (grepl("Seller",ii)){
    DV <- c("Dosage" ,"DosageInState","DosageOutState")
  } else {
    DV <- c("Dosage" ,"DosageInState","DosageOutState")
  }
  DVdict <- c(`Dosage` = "PCPV",
              `DosageBoarderBuyer` = "Boarder PCPV",
              `DosageNonBoarderBuyer` = "Inland PCPV",
              `DosageInState` = "In-State PCPV",
              `DosageOutState` = "Out-of-State PCPV")
  count = 1
  coef = data.table()
  for (jj in 1:length(DV)){
      for (kk in 1:length(IDV)){
        tmp <- fread(paste0(pathread,ii,'__',LawNames[kk],'__',DV[jj],'SA.csv'), header = T)
        rownames(coef) <- coef$V1
        tmp$V1 <- NULL
        tmp[,"DV"] <- DV[jj]
        tmp[,"IDV"] <- LawNames[kk]
        coef <- rbind(coef,tmp)
    }
  }
  setnames(coef, old = c('Pr(>|t|)','Pr(>|t|) Meta'), new = c('Pval','PvalMeta'))
  coef[, isSigMeta := 'InSig']
  coef[which(PvalMeta < 0.1 & EstimateMeta > 0), isSigMeta := 'SigPos']
  coef[which(PvalMeta < 0.1 & EstimateMeta < 0), isSigMeta := 'SigNeg']
  coef[which(PvalMeta > 0.1), isSigMeta := 'InSig']
  coef[,EffectMeta := ifelse(EstimateMeta > 0, 'positive','gray50')]
  coef[, EffectMean := ifelse(EstimateMeta > 0,
                              paste0('Avg. = ',round(EstimateMeta,3)),
                              paste0('Avg. = -',round(abs(EstimateMeta),3)))]
  PvalMeta = coef[,PvalMeta]
  coef[,ColorMeta := ifelse(isSigMeta == 'Sig', 'gray5','gray80')]
  coef = coef[which(0<= coef$Time & coef$Time < 20 & coef$Time != -3),]
  
  fig <- ggplot(coef,aes(x = Time,y = Estimate, ymin = Estimate - 1.96*SE,
                ymax= Estimate + 1.96*SE,
                color = Effect, linetype = isSig)) +
        facet_grid(DV ~ IDV ,scale='free_y',switch = "y",labeller = labeller(DV = DVdict, IDV = Lawdict))+
        geom_pointrange(aes(alpha=isSig), size = 0.1)+
        scale_alpha_manual(values=c('Sig'=1,'InSig'=0.5)) +
        scale_color_manual(values=c('positive'='blue','negative'='red','reference'='black'))+
        scale_fill_manual(values = c('SigPos'='royalblue1','SigNeg'='firebrick1','InSig'='white'))+
        scale_linetype_manual(values=c('Sig'='solid','InSig'='dotted'))+
        geom_ribbon(color='gray' ,alpha=0.2,linetype='solid')+
        geom_rect(aes(fill = isSigMeta),xmin = -Inf,xmax = Inf,ymin = -Inf,ymax = Inf,alpha = 0.01) +
        geom_hline(yintercept = 0, lty=2) +
        geom_vline(xintercept=0,linetype='dotted')+
        theme_pubr() +
        theme(axis.title.y = element_text(size=9))+
        guides(alpha=FALSE,
               fill=guide_legend(title=NULL),
               color=guide_legend(title=NULL),
               linetype=FALSE)+
        labs(y= "ATT",
             x='Quarters after policy adoption date') +
        theme(plot.subtitle = element_text(hjust = 0.5)) +
        theme(strip.text.x = element_text(size = 12),strip.text.y = element_text(size = 12),
              axis.text = element_text(size = 12)) +
        scale_x_continuous(n.breaks = 3) +
        theme(legend.position='none') + 
        geom_text(aes(x=min(Time) , y = 1.2*max(Estimate), label = coef$EffectMean),
                  color='black', size= 4, hjust="left",
                  family = "Times New Roman (Headings CS)")
  ggsave(paste0(pathwrite,ii,'.png'),fig)
  
  for (jj in DV){
    fig <- ggplot(coef[coef$DV == jj,],
                  aes(x = Time,y = Estimate, ymin = Estimate - 1.96*SE,
                ymax= Estimate + 1.96*SE,
                color = Effect, linetype = isSig)) +
        facet_grid(DV ~ IDV ,scale='free_y',switch = "y",labeller = labeller(DV = DVdict, IDV = Lawdict))+
        geom_pointrange(aes(alpha=isSig), size = 0.1)+
        scale_alpha_manual(values=c('Sig'=1,'InSig'=0.5)) +
        scale_color_manual(values=c('positive'='blue','negative'='red','reference'='black'))+
        scale_fill_manual(values = c('SigPos'='royalblue1','SigNeg'='firebrick1','InSig'='white'))+
        scale_linetype_manual(values=c('Sig'='solid','InSig'='dotted'))+
        geom_ribbon(color='gray' ,alpha=0.2,linetype='solid')+
        geom_rect(aes(fill = isSigMeta),xmin = -Inf,xmax = Inf,ymin = -Inf,ymax = Inf,alpha = 0.01) +
        geom_hline(yintercept = 0, lty=2) +
        geom_vline(xintercept=0,linetype='dotted')+
        theme_pubr() +
        theme(axis.title.y = element_text(size=9))+
        guides(alpha=FALSE,
               fill=guide_legend(title=NULL),
               color=guide_legend(title=NULL),
               linetype=FALSE)+
        labs(y= "ATT",
             x='Quarters after policy adoption date') +
        theme(plot.subtitle = element_text(hjust = 0.5)) +
        theme(strip.text.x = element_text(size = 14),strip.text.y = element_text(size = 14),
              axis.title.y  = element_text(family = "mono",size = 16, face = "bold"),
              axis.title.x  = element_text(family = "mono",size = 16, face = "bold"),
              axis.text = element_text(size = 14)) +
        scale_x_continuous(n.breaks = 3) +
        theme(legend.position='none') + 
        geom_text(aes(x=min(Time) , y = 1.2*max(Estimate), label = coef[coef$DV == jj]$EffectMean),
                  color='black', size= 6, hjust="left",
                  family = "Times New Roman (Headings CS)")
    ggsave(paste0(pathwrite,ii,jj,'2.png'),fig, width = 12, height = 6)
  }
} 

```









